package client;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import javax.swing.ImageIcon;

public interface GUIConstants {

	Character[] DIGIT_BUTTON_NAMES = {'7','8','9','4','5','6','1','2','3','0'};
	Character[] OPERATOR_BUTTON_NAMES = {'X',':','-','+'};
	String CLEAR_ENTRY_BUTTON_NAME = "CE";
	String CLEAR_BUTTON_NAME = "C";
	Character EQUALS_BUTTON_NAME = '=';
	Character POINT_BUTTON_NAME = '.';
	Character PLUS_MINUS_BUTTON_NAME = '\u00B1';
	Character BACK_BUTTON_NAME = '\u232B';
	Character SQUARE_ROOT_BUTTON_NAME = '\u221A';
	String SQUARE_BUTTON_NAME = "x\u00B2";
	Character PERCENTAGE_BUTTON_NAME = '\u0025';
	String ONE_DIVIDED_BY_X_BUTTON_NAME = "1/x";
	Character CHANGE_BUTTON_NAME = '\u2191';
	String GUI_TITLE = "Rechner";
	
	Dimension GUI_SIZE = new Dimension(320, 535);
	Dimension FORMULA_SIZE = new Dimension(300, 20);
	Dimension OUTPUT_SIZE = new Dimension(300, 80);
	
	String ERROR_TEXT = "ERROR";
	String NUMBER_WITH_POINT_AT_END_PATTERN = "\\-?\\d+\\.";
	String SERVER_IP1 = "192.168.5.106";
	String SERVER_IP2 = "169.254.181.207";
	
	Color GUI_BACKGROUND_COLOR = new Color(0, 0, 0);
	Color DIGIT_BUTTON_COLOR = new Color(50, 50, 50);
	Color DIGIT_BUTTON_TEXTCOLOR = new Color(200, 200, 200);
	Color OPERATOR_BUTTON_COLOR = new Color(0, 0, 0);
	Color OPERATOR_BUTTON_TEXTCOLOR = new Color(230, 230, 230);
	Color DEFAULT_BUTTON_COLOR = new Color(0, 0, 0);
	Color DEFAULT_BUTTON_TEXTCOLOR = new Color(250, 250, 250);
	
	Font OUTPUT_FONT = new Font("Haettenschweiler", Font.PLAIN, 50);
	Font FORMULA_FONT = new Font("Haettenschweiler", Font.PLAIN, 20);
	
	float GUI_OPACITY = 0.8f;
	
	ImageIcon CALCULATOR_ICON = new ImageIcon("C:/Users/rne/space/Rechner/externalFiles/calcIcon.jpg");
	
	int HGAP_BUTTONS = 5;
	int VGAP_BUTTONS = 5;
	int GRID_BUTTON_ROWS = 5;
	int GRID_BUTTON_COLUMNS = 4;
	int NUMBER_OF_BUTTONS = GRID_BUTTON_ROWS*GRID_BUTTON_COLUMNS;
	
	int GRID_POSITION_OPERATORS_DIVIDE = GUIConstants.GRID_BUTTON_COLUMNS;
	int GRID_POSITION_OPERATORS_MIN = GUIConstants.GRID_BUTTON_COLUMNS*(GUIConstants.GRID_BUTTON_ROWS-5);
	int GRID_POSITION_OPERATORS_MAX = GUIConstants.GRID_BUTTON_COLUMNS*(GUIConstants.GRID_BUTTON_ROWS-1);
	
	int GRID_POSITION_EQUALS = NUMBER_OF_BUTTONS-1;
	
	int GRID_POSITION_DIGITS_FIRST_LINE_MAX = ((GRID_BUTTON_COLUMNS)*(GRID_BUTTON_ROWS-4))+3+GRID_BUTTON_COLUMNS-4;
	int GRID_POSITION_DIGITS_FIRST_LINE_MIN = ((GRID_BUTTON_COLUMNS)*(GRID_BUTTON_ROWS-4))-1+GRID_BUTTON_COLUMNS-4;
	int GRID_POSITION_DIGITS_SECOND_LINE_MAX = GRID_POSITION_DIGITS_FIRST_LINE_MAX+GRID_BUTTON_COLUMNS;
	int GRID_POSITION_DIGITS_SECOND_LINE_MIN = GRID_POSITION_DIGITS_FIRST_LINE_MIN+GRID_BUTTON_COLUMNS;
	int GRID_POSITION_DIGITS_THIRD_LINE_MAX = GRID_POSITION_DIGITS_SECOND_LINE_MAX+GRID_BUTTON_COLUMNS;
	int GRID_POSITION_DIGITS_THIRD_LINE_MIN = GRID_POSITION_DIGITS_SECOND_LINE_MIN+GRID_BUTTON_COLUMNS;
	int GRID_POSITION_DIGITS_ZERO = GRID_POSITION_DIGITS_THIRD_LINE_MIN+GRID_BUTTON_COLUMNS+2;
	
	int GRID_POSTIION_CLEAR_ENTRY = GRID_POSITION_DIGITS_FIRST_LINE_MIN-GRID_BUTTON_COLUMNS+1;
	int GRID_POSITION_CLEAR = GRID_POSTIION_CLEAR_ENTRY+1;
	int GRID_POSITION_BACK = GRID_POSITION_CLEAR+1;
	
	int GRID_POSITION_PLUSMINUS = GRID_POSITION_DIGITS_THIRD_LINE_MIN+GRID_BUTTON_COLUMNS+1;
	int GRID_POSITION_POINT = GRID_POSITION_DIGITS_THIRD_LINE_MAX+GRID_BUTTON_COLUMNS-1;
	int GRID_POSITION_SQUARE_ROOT = GRID_POSITION_PLUSMINUS-1;
	int GRID_POSITION_SQUARE = GRID_POSITION_SQUARE_ROOT-GRID_BUTTON_COLUMNS;
	int GRID_POSITION_PERCENTAGE = GRID_POSITION_SQUARE-GRID_BUTTON_COLUMNS;
	int GRID_POSITION_ONE_DIVIDED_BY_X = GRID_POSITION_PERCENTAGE-GRID_BUTTON_COLUMNS;
	int GRID_POSITION_CHANGE = GRID_POSITION_ONE_DIVIDED_BY_X-GRID_BUTTON_COLUMNS;
}
